In [ ]:
use_local=False
if not use_local:
    with open(f'/g/g91/pandey2/.dftracer/configuration.yaml', 'r') as file:
        dlp_yaml = yaml.safe_load(file)
        app_root = dlp_yaml["app"]
else:
    app_root = str(Path(os.getcwd()).parent.parent)
sys.path.insert(0, app_root)

import dfanalyzer
print(dfanalyzer.__file__)
from dfanalyzer.main import DFAnalyzer,get_dft_configuration,update_dft_configuration,setup_logging,setup_dask_cluster, reset_dask_cluster, get_dft_configuration
from dfanalyzer.graph_visualization.cytoscape import GraphFunctions, CytoGraph
from dfanalyzer.graph import GraphIOXInterference

if not use_local:
    dask_run_dir = os.path.join(app_root, "dfanalyzer", "dask", "run_dir")
    with open (os.path.join(dask_run_dir, f"scheduler_{os.getenv('USER')}.json"), "r") as f:
        dask_scheduler = json.load(f)["address"]
else:
    dask_scheduler = None

# App Name
# app_name = "montage-pegasus-2mass-2deg-4node" #cosmoflow cm1

# app_name = "deepspeed-dlio-step100"
# app_name = "deepspeed-dlio-scr-step100"
app_name = "1000_genome_pegasus_node_16"
# app_name = "montage_pegasus-dss-1deg_node-16"
cp_dir =  "/p/lustre3/pandey2/logs/Results_Checkpoint"
# cp_dir = "/usr/workspace/pandey2/g_analyzer/B_notebooks/temp"

/usr/workspace/pandey2/DFT/dftracer/dfanalyzer/__init__.py

In [ ]:
data_events_obj = GraphIOXInterference(app_name=app_name, operation="data", cp_dir = cp_dir, existing=True)
data = data_events_obj.inter.compute()

In [17]:
nodes = len(data)
edges = (data['deg_caller'].sum() - nodes) / 2

print(nodes,edges)
print(len(data[data['deg_caller'] == 1]))

42928393 43031508.0
18441978

In [4]:
data["Interfered"] = np.where(data['deg_caller'] < 1 / data['interference'], "interfered", "not-interfered")
data['valid'] = (data['deg_caller'] > 1) & (data['dur'] > 0) & (data['interference'] > 0)

In [5]:
data.query("Interfered == 'interfered' and valid == True").groupby('hostname').count()

,name,cat,size,size_category,ts,te,dur,trange,mount_point,deg_caller,deg_other,min_dur,interference,Interfered,valid
hostname,,,,,,,,,,,,,,,
corona227,93705,93705,93705,93705,93705,93705,93705,93705,93705,93705,93705,93705,93705,93705,93705
corona229,55179,55179,55179,55179,55179,55179,55179,55179,55179,55179,55179,55179,55179,55179,55179
corona230,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507,2507
corona232,2610,2610,2610,2610,2610,2610,2610,2610,2610,2610,2610,2610,2610,2610,2610
corona233,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272
corona234,5618,5618,5618,5618,5618,5618,5618,5618,5618,5618,5618,5618,5618,5618,5618
corona235,2195,2195,2195,2195,2195,2195,2195,2195,2195,2195,2195,2195,2195,2195,2195
corona236,4920,4920,4920,4920,4920,4920,4920,4920,4920,4920,4920,4920,4920,4920,4920
corona237,5214,5214,5214,5214,5214,5214,5214,5214,5214,5214,5214,5214,5214,5214,5214
corona238,5249,5249,5249,5249,5249,5249,5249,5249,5249,5249,5249,5249,5249,5249,5249
corona239,5281,5281,5281,5281,5281,5281,5281,5281,5281,5281,5281,5281,5281,5281,5281
corona240,2406,2406,2406,2406,2406,2406,2406,2406,2406,2406,2406,2406,2406,2406,2406
corona241,3216,3216,3216,3216,3216,3216,3216,3216,3216,3216,3216,3216,3216,3216,3216
corona242,3842,3842,3842,3842,3842,3842,3842,3842,3842,3842,3842,3842,3842,3842,3842
corona243,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654,2654
corona244,1889,1889,1889,1889,1889,1889,1889,1889,1889,1889,1889,1889,1889,1889,1889

In [9]:
data.query('valid == "True"')

,name,cat,size,size_category,ts,te,dur,trange,mount_point,hostname,deg_caller,deg_other,min_dur,interference,Interfered,valid
69,read,POSIX,2,2^0 - 2^1 B,1276648,1276695,47,1,/,corona234,2,1.0,17.0,0.361702,interfered,True
70,read,POSIX,2,2^0 - 2^1 B,1276686,1276725,39,1,/,corona240,2,1.0,17.0,0.435897,interfered,True
94,read,POSIX,2,2^0 - 2^1 B,1314252,1314306,54,1,/,corona233,2,1.0,17.0,0.314815,interfered,True
95,read,POSIX,2,2^0 - 2^1 B,1314262,1314299,37,1,/,corona242,2,1.0,17.0,0.459459,interfered,True
104,read,POSIX,27,2^4 - 2^5 B,1333208,1333265,57,1,/,corona242,2,1.0,15.0,0.263158,interfered,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7131,fread,STDIO,28800,2^4 KiB - 2^5 KiB,1919527910,1919527930,20,1919,/p/lustre3,corona229,2,1.0,6.0,0.3,interfered,True
7132,fread,STDIO,28800,2^4 KiB - 2^5 KiB,1919528694,1919528713,19,1919,/p/lustre3,corona229,2,1.0,6.0,0.315789,interfered,True
7133,fread,STDIO,28800,2^4 KiB - 2^5 KiB,1919529494,1919529514,20,1919,/p/lustre3,corona229,2,1.0,6.0,0.3,interfered,True
7134,fread,STDIO,28800,2^4 KiB - 2^5 KiB,1919530276,1919530295,19,1919,/p/lustre3,corona229,2,1.0,6.0,0.315789,interfered,True
7135,fread,STDIO,28800,2^4 KiB - 2^5 KiB,1919531063,1919531084,21,1919,/p/lustre3,corona229,2,1.0,6.0,0.285714,interfered,True

In [12]:

data['mount_point'] = data['mount_point'].replace('/p/lustre2', '/p/lustre3')
data.query('valid == True').groupby('mount_point').count()

,name,cat,size,size_category,ts,te,dur,trange,hostname,deg_caller,deg_other,min_dur,interference,Interfered,valid
mount_point,,,,,,,,,,,,,,,
/,3621,3621,3621,3621,3621,3621,3621,3621,3621,3621,3621,3621,3621,3621,3621
/p/lustre3,262194,262194,262194,262194,262194,262194,262194,262194,262194,262194,262194,262194,262194,262194,262194
/sys,83748,83748,83748,83748,83748,83748,83748,83748,83748,83748,83748,83748,83748,83748,83748
/tmp,7947,7947,7947,7947,7947,7947,7947,7947,7947,7947,7947,7947,7947,7947,7947

In [6]:
data.to_csv("/p/lustre3/pandey2/logs/Results_Checkpoint/csvs/IF_data/"+app_name+".csv")

# deepspeed-100

In [ ]:
data_events_obj = GraphIOXInterference(app_name=app_name, operation="data", cp_dir = cp_dir, existing=True)
metadata_events_obj = GraphIOXInterference(app_name=app_name, operation="metadata", cp_dir = cp_dir, existing=True)

data = data_events_obj.inter.compute()
metadata = metadata_events_obj.inter.compute()

data["Operation"] = "Data"
metadata["Operation"] = "Metadata"
data["Interfered"] = np.where(data['deg_caller'] < 1 / data['interference'], "interfered", "not-interfered")
metadata["Interfered"] = np.where(metadata['deg_caller'] < 1 / metadata['interference'], "interfered", "not-interfered")
all_ops = pd.concat([data,metadata])
all_ops['valid'] = (all_ops['deg_caller'] > 1) & (all_ops['dur'] > 0) & (all_ops['interference'] > 0)

In [5]:
all_ops.to_csv("deepspeed-dlio-step100.csv")

# deepspeed-dlio-scr-step100

In [8]:
app_name

'deepspeed-dlio-scr-step100'

In [ ]:
data_events_obj = GraphIOXInterference(app_name=app_name, operation="data", cp_dir = cp_dir, existing=True)
metadata_events_obj = GraphIOXInterference(app_name=app_name, operation="metadata", cp_dir = cp_dir, existing=True)

data = data_events_obj.inter.compute()
metadata = metadata_events_obj.inter.compute()

data["Operation"] = "Data"
metadata["Operation"] = "Metadata"
data["Interfered"] = np.where(data['deg_caller'] < 1 / data['interference'], "interfered", "not-interfered")
metadata["Interfered"] = np.where(metadata['deg_caller'] < 1 / metadata['interference'], "interfered", "not-interfered")
all_ops = pd.concat([data,metadata])
all_ops['valid'] = (all_ops['deg_caller'] > 1) & (all_ops['dur'] > 0) & (all_ops['interference'] > 0)

In [13]:
all_ops.to_csv("deepspeed-dlio-scr-step100.csv")

# CM1

In [ ]:
data_events_obj = GraphIOXInterference(app_name=app_name, operation="data", cp_dir = cp_dir, existing=True)
metadata_events_obj = GraphIOXInterference(app_name=app_name, operation="metadata", cp_dir = cp_dir, existing=True)

data = data_events_obj.inter.compute()
metadata = metadata_events_obj.inter.compute()

data["Operation"] = "Data"
metadata["Operation"] = "Metadata"
data["Interfered"] = np.where(data['deg_caller'] < 1 / data['interference'], "interfered", "not-interfered")
metadata["Interfered"] = np.where(metadata['deg_caller'] < 1 / metadata['interference'], "interfered", "not-interfered")
all_ops = pd.concat([data,metadata])
all_ops['valid'] = (all_ops['deg_caller'] > 1) & (all_ops['dur'] > 0) & (all_ops['interference'] > 0)

In [18]:
all_ops.to_csv("cm1.csv")

# Resnet50

In [20]:
app_name

'resnet50'

In [ ]:
data_events_obj = GraphIOXInterference(app_name=app_name, operation="data", cp_dir = cp_dir, existing=True)
metadata_events_obj = GraphIOXInterference(app_name=app_name, operation="metadata", cp_dir = cp_dir, existing=True)

data = data_events_obj.inter.compute()
metadata = metadata_events_obj.inter.compute()

data["Operation"] = "Data"
metadata["Operation"] = "Metadata"
data["Interfered"] = np.where(data['deg_caller'] < 1 / data['interference'], "interfered", "not-interfered")
metadata["Interfered"] = np.where(metadata['deg_caller'] < 1 / metadata['interference'], "interfered", "not-interfered")
all_ops = pd.concat([data,metadata])
all_ops['valid'] = (all_ops['deg_caller'] > 1) & (all_ops['dur'] > 0) & (all_ops['interference'] > 0)

In [23]:
all_ops.to_csv("resnet50.csv")

In [79]:
all_ops.query("valid == True")

,name,cat,size,size_category,ts,te,dur,trange,mount_point,hostname,deg_caller,deg_other,min_dur,interference,Operation,Interfered,valid
0,read,POSIX,4025,2048-4096,64312,65124,812,0,/collab/usr/gapps,corona191,8,1,2,0.002463,Data,interfered,True
1,read,POSIX,4025,2048-4096,64608,65126,518,0,/collab/usr/gapps,corona191,8,1,2,0.003861,Data,interfered,True
2,read,POSIX,4025,2048-4096,64627,65128,501,0,/collab/usr/gapps,corona191,8,1,2,0.003992,Data,interfered,True
3,read,POSIX,4025,2048-4096,64631,65131,500,0,/collab/usr/gapps,corona191,8,1,2,0.004,Data,interfered,True
4,read,POSIX,4025,2048-4096,64922,65130,208,0,/collab/usr/gapps,corona191,8,1,2,0.009615,Data,interfered,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16614,unlink,POSIX,0,size,7444565648,7444565654,6,7444,/dev/shm,corona192,4,1,3,0.5,Metadata,not-interfered,True
16621,unlink,POSIX,0,size,7444565661,7444565668,7,7444,/dev/shm,corona198,9,1,3,0.428571,Metadata,not-interfered,True
16646,unlink,POSIX,0,size,7444565689,7444565701,12,7444,/dev/shm,corona191,11,1,3,0.25,Metadata,not-interfered,True
16668,unlink,POSIX,0,size,7444565721,7444565726,5,7444,/dev/shm,corona199,8,1,3,0.6,Metadata,not-interfered,True
17179,open64,POSIX,0,size,92876277,92876326,49,92,/proc,corona223,4,1,5,0.102041,Metadata,interfered,True

In [70]:
all_ops.query("deg_caller > 1 and dur > 0 and interference > 0")

,name,cat,size,size_category,ts,te,dur,trange,mount_point,hostname,deg_caller,deg_other,min_dur,interference,Operation,Interfered
0,read,POSIX,4025,2048-4096,64312,65124,812,0,/collab/usr/gapps,corona191,8,1,2,0.002463,Data,interfered
1,read,POSIX,4025,2048-4096,64608,65126,518,0,/collab/usr/gapps,corona191,8,1,2,0.003861,Data,interfered
2,read,POSIX,4025,2048-4096,64627,65128,501,0,/collab/usr/gapps,corona191,8,1,2,0.003992,Data,interfered
3,read,POSIX,4025,2048-4096,64631,65131,500,0,/collab/usr/gapps,corona191,8,1,2,0.004,Data,interfered
4,read,POSIX,4025,2048-4096,64922,65130,208,0,/collab/usr/gapps,corona191,8,1,2,0.009615,Data,interfered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16614,unlink,POSIX,0,size,7444565648,7444565654,6,7444,/dev/shm,corona192,4,1,3,0.5,Metadata,not-interfered
16621,unlink,POSIX,0,size,7444565661,7444565668,7,7444,/dev/shm,corona198,9,1,3,0.428571,Metadata,not-interfered
16646,unlink,POSIX,0,size,7444565689,7444565701,12,7444,/dev/shm,corona191,11,1,3,0.25,Metadata,not-interfered
16668,unlink,POSIX,0,size,7444565721,7444565726,5,7444,/dev/shm,corona199,8,1,3,0.6,Metadata,not-interfered
17179,open64,POSIX,0,size,92876277,92876326,49,92,/proc,corona223,4,1,5,0.102041,Metadata,interfered

In [75]:
all_ops

,name,cat,size,size_category,ts,te,dur,trange,mount_point,hostname,deg_caller,deg_other,min_dur,interference,Operation,Interfered,valid
0,read,POSIX,4025,2048-4096,64312,65124,812,0,/collab/usr/gapps,corona191,8,1,2,0.002463,Data,interfered,True
1,read,POSIX,4025,2048-4096,64608,65126,518,0,/collab/usr/gapps,corona191,8,1,2,0.003861,Data,interfered,True
2,read,POSIX,4025,2048-4096,64627,65128,501,0,/collab/usr/gapps,corona191,8,1,2,0.003992,Data,interfered,True
3,read,POSIX,4025,2048-4096,64631,65131,500,0,/collab/usr/gapps,corona191,8,1,2,0.004,Data,interfered,True
4,read,POSIX,4025,2048-4096,64922,65130,208,0,/collab/usr/gapps,corona191,8,1,2,0.009615,Data,interfered,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17388,__fxstat64,POSIX,0,size,92997933,92997937,4,92,/proc,corona221,1,1,0,0.0,Metadata,interfered,False
17389,lseek64,POSIX,0,size,92997949,92997951,2,92,/proc,corona221,1,1,0,0.0,Metadata,interfered,False
17390,lseek64,POSIX,0,size,92997964,92997965,1,92,/proc,corona221,1,1,0,0.0,Metadata,interfered,False
17391,__fxstat64,POSIX,0,size,92997980,92997980,0,92,/proc,corona221,1,1,0,NaN,Metadata,not-interfered,False
17392,close,POSIX,0,size,92998025,92998030,5,92,/proc,corona221,1,1,1,0.2,Metadata,interfered,False

In [76]:
all_ops.groupby('valid')["deg_caller"].mean()

valid
False     3.413420
True     43.741178
Name: deg_caller, dtype: float64

In [60]:
all_ops[all_ops["interference" ] > 0].query('Interfered == "interfered"')

,name,cat,size,size_category,ts,te,dur,trange,mount_point,hostname,deg_caller,deg_other,min_dur,interference,Operation,Interfered
0,read,POSIX,4025,2048-4096,64312,65124,812,0,/collab/usr/gapps,corona191,8,1,2,0.002463,Data,interfered
1,read,POSIX,4025,2048-4096,64608,65126,518,0,/collab/usr/gapps,corona191,8,1,2,0.003861,Data,interfered
2,read,POSIX,4025,2048-4096,64627,65128,501,0,/collab/usr/gapps,corona191,8,1,2,0.003992,Data,interfered
3,read,POSIX,4025,2048-4096,64631,65131,500,0,/collab/usr/gapps,corona191,8,1,2,0.004,Data,interfered
4,read,POSIX,4025,2048-4096,64922,65130,208,0,/collab/usr/gapps,corona191,8,1,2,0.009615,Data,interfered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17380,close,POSIX,0,size,92992612,92992617,5,92,/proc,corona221,1,1,1,0.2,Metadata,interfered
17381,open64,POSIX,0,size,92995907,92995948,41,92,/proc,corona221,1,1,5,0.121951,Metadata,interfered
17386,close,POSIX,0,size,92996060,92996065,5,92,/proc,corona221,1,1,1,0.2,Metadata,interfered
17387,open64,POSIX,0,size,92997883,92997920,37,92,/proc,corona221,1,1,5,0.135135,Metadata,interfered
17392,close,POSIX,0,size,92998025,92998030,5,92,/proc,corona221,1,1,1,0.2,Metadata,interfered